/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false --strict-vars false` (hash: c834e771c5925a771b877d48c8b8ee17)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/index');
  }
  interface Env {
    DISPATCH_NAMESPACE_NAME: string;
    CUSTOM_DOMAIN: string;
    DISPATCH_NAMESPACE_API_TOKEN: string;
    CLOUDFLARE_ACCOUNT_ID: string;
    CLOUDFLARE_ZONE_ID: string;
    CLOUDFLARE_API_TOKEN: string;
    FALLBACK_ORIGIN: string;
    WORKERS_DEV_SUBDOMAIN: string;
    DB: D1Database;
    dispatcher: DispatchNamespace;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | 'DISPATCH_NAMESPACE_NAME'
        | 'CUSTOM_DOMAIN'
        | 'DISPATCH_NAMESPACE_API_TOKEN'
        | 'CLOUDFLARE_ACCOUNT_ID'
        | 'CLOUDFLARE_ZONE_ID'
        | 'CLOUDFLARE_API_TOKEN'
        | 'FALLBACK_ORIGIN'
        | 'WORKERS_DEV_SUBDOMAIN'
      >
    > {}
}
